update toolchain

diff --git a/lib32-glibc/PKGBUILD b/lib32-glibc/PKGBUILD
--- a/lib32-glibc/PKGBUILD
+++ b/lib32-glibc/PKGBUILD
@@ -5,38 +5,40 @@
 
 _pkgbasename=glibc
 pkgname=lib32-$_pkgbasename
-pkgver=2.19
-pkgrel=3
+pkgver=2.20
+pkgrel=1
 pkgdesc="GNU C Library (32-bit)"
 arch=('x86_64')
 url="http://www.gnu.org/software/libc"
 license=('GPL' 'LGPL')
 #depends=($_pkgbasename=$pkgver)
-makedepends=('gcc-multilib>=4.8')
+makedepends=('gcc-multilib>=4.9')
 options=('!strip' '!emptydirs' 'staticlibs')
 source=(http://ftp.gnu.org/gnu/libc/${_pkgbasename}-${pkgver}.tar.xz{,.sig}
-        glibc-2.19-xattr_header.patch
-        glibc-2.19-fix-sign-in-bsloww1-input.patch
-        glibc-2.19-tzselect-default.patch
+	glibc-2.20-getifaddrs_internal-segfault.patch
+	glibc-2.20-linux-3.16-additions.patch
+	glibc-2.20-do_ftell_wide-memleak.patch
         lib32-glibc.conf)
-md5sums=('e26b8cc666b162f999404b03970f14e4'
+md5sums=('948a6e06419a01bd51e97206861595b0'
          'SKIP'
-         '39a4876837789e07746f1d84cd8cb46a'
-         '755a1a9d7844a5e338eddaa9a5d974cd'
-         'c772dc99ddd8032ecbf43884ae0cf42e'
+         '1c5d5c2017445c75dbc5c6d0c1e45ddb'
+         '8f1059f431b842e54b12bde689620df8'
+         'b50feeab78fa6ce0a8cfb41ee8dc1fd8'
          '6e052f1cb693d5d3203f50f9d4e8c33b')
+validpgpkeys=('F37CDAB708E65EA183FD1AF625EF0A436C2A4AFF')  # Carlos O'Donell
 
 prepare() {
-  cd ${srcdir}/${_pkgbasename}-${pkgver}
+  cd ${srcdir}/glibc-${pkgver}
 
-  # fix for {linux,sys}/xattr.h incompatibility - commit fdbe8eae
-  patch -p1 -i $srcdir/glibc-2.19-xattr_header.patch
-
-  # fix issues in sin/cos slow path calculation - commit ffe768a9
-  patch -p1 -i $srcdir/glibc-2.19-fix-sign-in-bsloww1-input.patch
-
-  # fix tzselect with missing TZDIR - commit 893b4f37/c72399fb
-  patch -p1 -i $srcdir/glibc-2.19-tzselect-default.patch
+  # fix segfault in getifaddrs_internal
+  # https://sourceware.org/ml/libc-alpha/2014-09/msg00312.html
+  patch -p1 -i $srcdir/glibc-2.20-getifaddrs_internal-segfault.patch
+  
+  # linux 3.16 additions - commit 0bd72468
+  patch -p1 -i $srcdir/glibc-2.20-linux-3.16-additions.patch
+  
+  # plug memory leak - commit 984c0ea9
+  patch -p1 -i $srcdir/glibc-2.20-do_ftell_wide-memleak.patch
 
   mkdir ${srcdir}/glibc-build
 }
@@ -51,19 +53,20 @@ build() {
   #fi
 
   echo "slibdir=/usr/lib32" >> configparms
+  echo "rtlddir=/usr/lib32" >> configparms
 
   export CC="gcc -m32"
   export CXX="g++ -m32"
 
   # remove hardening options for building libraries
-  CFLAGS=${CFLAGS/-fstack-protector/}
+  CFLAGS=${CFLAGS/-fstack-protector-strong/}
   CPPFLAGS=${CPPFLAGS/-D_FORTIFY_SOURCE=2/}
 
   ${srcdir}/${_pkgbasename}-${pkgver}/configure --prefix=/usr \
       --libdir=/usr/lib32 --libexecdir=/usr/lib32 \
       --with-headers=/usr/include \
       --with-bugurl=http://chakraos.org/bugtracker\
-      --enable-add-ons=nptl,libidn \
+      --enable-add-ons \
       --enable-obsolete-rpc \
       --enable-kernel=2.6.32 \
       --enable-bind-now --disable-profile \
@@ -77,12 +80,12 @@ build() {
 
   # re-enable hardening for programs
   sed -i "/build-programs=/s#no#yes#" configparms
-  echo "CC += -fstack-protector -D_FORTIFY_SOURCE=2" >> configparms
-  echo "CXX += -fstack-protector -D_FORTIFY_SOURCE=2" >> configparms
+  echo "CC += -fstack-protector-strong -D_FORTIFY_SOURCE=2" >> configparms
+  echo "CXX += -fstack-protector-strong -D_FORTIFY_SOURCE=2" >> configparms
   make
 
   # remove harding in preparation to run test-suite
-  sed -i '4,6d' configparms
+  sed -i '5,7d' configparms
 }
 
 check() {
@@ -90,7 +93,9 @@ check() {
   LDFLAGS=${LDFLAGS/--as-needed,/}
 
   cd ${srcdir}/glibc-build
-  make -k check || true
+
+  # tst-cleanupx4 failure on i686 is "expected"
+  make check || true
 }
 
 package() {
@@ -104,17 +109,15 @@ package() {
 
 
   # Dynamic linker
-  # install -d -m755 ${pkgdir}/usr/lib
-  install -d -m755 ${pkgdir}/lib
-  # ln -s ../lib32/ld-linux.so.2 ${pkgdir}/usr/lib/ # no reason yet to install in /usr/lib too, only needed once we also move lib
-  ln -s ../usr/lib32/ld-linux.so.2 ${pkgdir}/lib/ 
+  install -d -m755 ${pkgdir}/usr/lib
+  ln -s ../lib32/ld-linux.so.2 ${pkgdir}/usr/lib/
 
   # Add lib32 paths to the default library search path
   install -Dm644 "$srcdir/lib32-glibc.conf" "$pkgdir/etc/ld.so.conf.d/lib32-glibc.conf"
 
   # Symlink /usr/lib32/locale to /usr/lib/locale
   ln -s ../lib/locale "$pkgdir/usr/lib32/locale"
-  
+
   # remove the static libraries that have a shared counterpart
   # libc, libdl, libm and libpthread are required for toolchain testsuites
   # in addition libcrypt appears widely required
