Toolchain build for lib32

diff --git a/gcc-multilib/PKGBUILD b/gcc-multilib/PKGBUILD
--- a/gcc-multilib/PKGBUILD
+++ b/gcc-multilib/PKGBUILD
@@ -6,11 +6,10 @@
 
 pkgbase='gcc-multilib'
 pkgname=('gcc-multilib' 'gcc-libs-multilib' 'lib32-gcc-libs' 'gcc-fortran-multilib' 'gcc-objc-multilib' 'gcc-ada-multilib')
-pkgver=4.5.1
-pkgrel=1
-_corerel=1 # core/gcc pkgrel this is based on
+pkgver=4.5.2
+pkgrel=2
 #_snapshot=4.5-20100610
-_libstdcppmanver=20100719	# Note: check source directory name when updating this
+_libstdcppmanver=4.5.2     # Note: check source directory name when updating this
 pkgdesc="The GNU Compiler Collection for multilib"
 arch=('x86_64')
 license=('GPL' 'LGPL' 'custom')
@@ -18,17 +17,18 @@ url="http://gcc.gnu.org"
 makedepends=('binutils-multilib>=2.20.1' 'libmpc>=0.8.2-1' 'cloog-ppl>=0.15.9-2' 'elfutils' 'gcc-ada-multilib'
              'glibc>=2.11.1-2' 'lib32-glibc>=2.12.1')
 options=('!libtool' '!emptydirs')
-source=(ftp://gcc.gnu.org/pub/gcc/releases/gcc-${pkgver}/gcc-{core,g++,fortran,objc,ada}-${pkgver}.tar.bz2
-	#ftp://gcc.gnu.org/pub/gcc/snapshots/${_snapshot}/gcc-{core,g++,fortran,objc,ada}-${_snapshot}.tar.bz2
-	ftp://gcc.gnu.org/pub/gcc/libstdc++/doxygen/libstdc++-api.${_libstdcppmanver}.man.tar.bz2
+source=(ftp://gcc.gnu.org/pub/gcc/releases/gcc-${pkgver}/gcc-{core,g++,fortran,objc,ada,testsuite}-${pkgver}.tar.bz2
+	#ftp://gcc.gnu.org/pub/gcc/snapshots/${_snapshot}/gcc-{core,g++,fortran,objc,ada,testsuite}-${_snapshot}.tar.bz2
+	ftp://gcc.gnu.org/pub/gcc/libstdc++/doxygen/libstdc++-api-${_libstdcppmanver}.man.tar.bz2
 	gcc_pure64.patch
 	gcc-hash-style-both.patch)
-md5sums=('dc8959e31b01a65ce10d269614815054'
-         'b294953ff0bb2f20c7acb2bf005d832a'
-         '7567c2f8df8a8bf61b48fe414b88de65'
-         '3c11b7037896e967eddf8178af2ddd98'
-         'c92111e2e22fc60d1e0adb1b5c7fa4f9'
-         '226ae0c6364cfe2c1f7ac88d06088d5a'
+md5sums=('aa9e36bec080452372bfba793428ee82'
+         '9821f1c61e43755866861485ff364e90'
+         '8cc545fda70085c78076d79e0e23962a'
+         '3561c6585e9062105cc3591a8c39d7dc'
+         'ee24023972f337fbc22202d6d219a727'
+         '29ae615438aba0bd3384b94bac54c235'
+         '2776eab5ebb7f9cc62dd2199a3a24382'
          '22cec272f9cc2801d3cd348feaca888b'
          '6fd395bacbd7b6e47c7b74854b478363')
 
@@ -40,11 +40,6 @@ else
 fi
 
 build() {
-  if ! locale -a | grep ^de_DE > /dev/null; then
-    echo "You need the de_DE locale to build gcc."
-    return 1
-  fi
-  
   cd ${_basedir}
 
   # "Add" ppl-0.11 compatibility
@@ -56,37 +51,44 @@ build() {
   # Do not run fixincludes
   sed -i 's@\./fixinc\.sh@-c true@' gcc/Makefile.in
 
-  if [ "${CARCH}" = "x86_64" ]; then
-    patch -Np1 -i ../gcc_pure64.patch
-  fi
+  patch -Np1 -i ${srcdir}/gcc_pure64.patch
   patch -Np0 -i ${srcdir}/gcc-hash-style-both.patch
 
   echo ${pkgver} > gcc/BASE-VER
 
-  # Add PATH for pod2man. Needed for manpages
-  export PATH="$PATH:/usr/lib/perl5/core_perl/bin"
-
-  mkdir build && cd build      
-  ../configure --prefix=/usr --enable-languages=c,c++,fortran,objc,obj-c++,ada \
+  cd ${srcdir}
+  mkdir gcc-build && cd gcc-build
+  ${_basedir}/configure --prefix=/usr \
+      --enable-languages=c,c++,fortran,objc,obj-c++,ada \
       --enable-shared --enable-threads=posix --enable-__cxa_atexit \
       --enable-clocale=gnu --enable-gnu-unique-object \
       --enable-lto --enable-plugin \
+      --enable-gold --with-plugin-ld=ld.gold \
       --enable-multilib --disable-libstdcxx-pch \
-      --with-system-zlib --with-ppl --with-cloog \
+      --with-system-zlib --with-ppl \
+      --with-cloog --with-cloog-include=/usr/include/cloog-ppl \
       --libdir=/usr/lib --libexecdir=/usr/lib \
       --mandir=/usr/share/man --infodir=/usr/share/info
   make
+
+  # increase stack size to prevent test failures
+  # http://gcc.gnu.org/bugzilla/show_bug.cgi?id=31827
+  ulimit -s 32768
+
+  # do not abort on error as some are "expected"
+  make -k check || true
+  ${_basedir}/contrib/test_summary
 }
 
 package_gcc-libs-multilib()
 {
-  pkgdesc="Runtime libraries shipped by GCC for C and C++ languages for multilib"
+  pkgdesc="Runtime libraries shipped by GCC for multilib"
   depends=('glibc>=2.11.1-2' "lib32-gcc-libs=$pkgver-$pkgrel")
-  provides=("gcc-libs=$pkgver-$_corerel")
+  provides=("gcc-libs=$pkgver-$pkgrel")
   conflicts=('gcc-libs')
   install=gcc-libs.install
 
-  cd ${_basedir}/build
+  cd gcc-build
   make -j1 -C $CHOST/libgcc DESTDIR=${pkgdir} install-shared
   for lib in libmudflap libgomp libssp libstdc++-v3/src; do
     make -j1 -C $CHOST/$lib DESTDIR=${pkgdir} install-toolexeclibLTLIBRARIES
@@ -97,7 +99,6 @@ package_gcc-libs-multilib()
   make -j1 DESTDIR=${pkgdir} install-target-libgfortran
 
   make -j1 DESTDIR=${pkgdir} install-target-libobjc
-
   # I thought I said to only install the lib...
   rm -rf ${pkgdir}/usr/lib/gcc/
   rm -rf ${pkgdir}/usr/lib32
@@ -112,10 +113,10 @@ package_gcc-libs-multilib()
 
 package_lib32-gcc-libs()
 {
-  pkgdesc="Runtime libraries shipped by GCC for C and C++ languages (32-bit)"
-  depends=('lib32-glibc>=2.12.1' "gcc-libs>=$pkgver-$_corerel")
+  pkgdesc="Runtime libraries shipped by GCC (32-bit)"
+  depends=('lib32-glibc>=2.12.1' "gcc-libs")
 
-  cd ${_basedir}/build
+  cd gcc-build
   make -j1 -C $CHOST/32/libgcc DESTDIR=${pkgdir} install-shared
   for lib in libmudflap libgomp libssp libstdc++-v3/src; do
     make -j1 -C $CHOST/32/$lib DESTDIR=${pkgdir} install-toolexeclibLTLIBRARIES
@@ -138,13 +139,15 @@ package_lib32-gcc-libs()
 
 package_gcc-multilib()
 {
-  depends=('binutils-multilib>=2.20.1' 'libmpc>=0.8.1-2' 'cloog-ppl>=0.15.9-2' 'elfutils' \
+  pkgdesc="The GNU Compiler Collection - C and C++ frontends for multilib"
+  depends=('binutils-multilib>=2.20' 'libmpc>=0.8.1-2' 'cloog-ppl>=0.15.9-2' 'elfutils' \
            "gcc-libs-multilib=$pkgver-$pkgrel")
-  provides=("gcc=$pkgver-$_corerel")
+  groups=('multilib-devel')
+  provides=("gcc=$pkgver-$pkgrel")
   conflicts=('gcc')
   install=gcc.install
 
-  cd ${_basedir}/build
+  cd gcc-build
   
   # much, much easier to install the lot and clean-up the mess
   make -j1 DESTDIR=${pkgdir} install
@@ -195,8 +198,6 @@ EOF
   install -dm755 ${pkgdir}/usr/share/man/man3
   install -m644 ${srcdir}/libstdc++-api-${_libstdcppmanver}.man/man3/* \
     ${pkgdir}/usr/share/man/man3/
-  # deal with conflicts...
-  rm -f ${pkgdir}/usr/share/man/man3/{ctime,queue,random,regex,string}.3
 
   # Install Runtime Library Exception
   install -Dm644 ${_basedir}/COPYING.RUNTIME \
@@ -207,11 +208,11 @@ package_gcc-fortran-multilib()
 {
   pkgdesc="Fortran front-end for GCC for multilib"
   depends=("gcc-multilib=$pkgver-$pkgrel")
-  provides=("gcc-fortran=$pkgver-$_corerel")
+  provides=("gcc-fortran=$pkgver-$pkgrel")
   conflicts=('gcc-fortran')
   install=gcc-fortran.install
 
-  cd ${_basedir}/build
+  cd gcc-build
   make -j1 DESTDIR=$pkgdir install-target-libgfortran
   make -j1 -C $CHOST/libgomp DESTDIR=$pkgdir install-nodist_fincludeHEADERS
   make -j1 -C gcc DESTDIR=$pkgdir fortran.install-{common,man,info}
@@ -229,10 +230,10 @@ package_gcc-objc-multilib()
 {
   pkgdesc="Objective-C front-end for GCC for multilib"
   depends=("gcc-multilib=$pkgver-$pkgrel")
-  provides=("gcc-objc=$pkgver-$_corerel")
+  provides=("gcc-objc=$pkgver-$pkgrel")
   conflicts=('gcc-objc')
 
-  cd ${_basedir}/build
+  cd gcc-build
   make -j1 DESTDIR=$pkgdir install-target-libobjc
   install -dm755 $pkgdir/usr/lib/gcc/$CHOST/$pkgver/
   install -m755 gcc/cc1obj{,plus} $pkgdir/usr/lib/gcc/$CHOST/$pkgver/
@@ -249,11 +250,11 @@ package_gcc-ada-multilib()
 {
   pkgdesc="Ada front-end for GCC (GNAT) for multilib"
   depends=("gcc-multilib=$pkgver-$pkgrel")
-  provides=("gcc-ada=$pkgver-$_corerel")
+  provides=("gcc-ada=$pkgver-$pkgrel")
   conflicts=('gcc-ada')
   install=gcc-ada.install
 
-  cd ${_basedir}/build
+  cd gcc-build
   make -j1 -C gcc DESTDIR=$pkgdir ada.install-{common,info}
   install -m755 gcc/gnat1 $pkgdir/usr/lib/gcc/$CHOST/$pkgver
   make -j1 -C $CHOST/32/libada DESTDIR=${pkgdir} install-gnatlib
