New tc

diff --git a/binutils-multilib/PKGBUILD b/binutils-multilib/PKGBUILD
--- a/binutils-multilib/PKGBUILD
+++ b/binutils-multilib/PKGBUILD
@@ -5,49 +5,55 @@
 
 # toolchain build order: linux-api-headers->glibc->binutils->gcc->binutils->glibc
 
-pkgname=binutils-multilib
 _pkgname=binutils
-pkgver=2.20.1
-pkgrel=2
-_date=20100908
+pkgname=binutils-multilib
+pkgver=2.21.1
+pkgrel=1
+_date=20110627
 pkgdesc="A set of programs to assemble and manipulate binary and object files for multilib"
 arch=('x86_64')
 url="http://www.gnu.org/software/binutils/"
 license=('GPL')
+groups=('multilib-devel')
 provides=("binutils=$pkgver-$pkgrel")
 conflicts=('binutils')
-depends=('glibc>=2.12-1' 'zlib')
-makedepends=('gcc-multilib') # Make sure we compile this with gcc-multilib
+depends=('glibc>=2.14' 'zlib')
+makedepends=('dejagnu' 'gcc-multilib') # Make sure we compile this with gcc-multilib
 options=('!libtool' '!distcc' '!ccache')
 install=binutils.install
 source=(http://chakra-project.org/sources/${_pkgname}/${_pkgname}-${pkgver}_${_date}.tar.bz2)
-md5sums=('c653cd51d2c23129cb010ac8c9ce0582')
+md5sums=('2face559e80d649ba148e42bb2d1fb0f')
 
 build() {
   cd ${srcdir}
-  mkdir build && cd build
+  mkdir binutils-build && cd binutils-build
 
-  CC="gcc -L`pwd`/bfd/.libs/"
-  if [ "${CARCH}" = "x86_64" ]; then
-    ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-64-bit-bfd
-  else
-    ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared
-  fi
-  # fix man files install path
-  sed -i -e "s:mandir \= \/usr\/share:mandir \= ${pkgdir}\/usr\/share:" ${srcdir}/build/Makefile || return 1
-  # fix info files install path
-  sed -i -e "s:infodir \= \/usr\/share:infodir \= ${pkgdir}\/usr\/share:" ${srcdir}/build/Makefile || return 1
+  ${srcdir}/binutils/configure --prefix=/usr \
+    --enable-ld=default --enable-gold \
+    --enable-plugins --enable-threads \
+    --enable-shared \
+    --enable-64-bit-bfd --enable-multilib
 
-  # This checks the host environment and makes sure all the necessary tools are available to compile Binutils.
-  make configure-host || return 1
+  # check the host environment and makes sure all the necessary tools are available
+  make configure-host
 
-  make tooldir=${pkgdir}/usr || return 1
+  make tooldir=${pkgdir}/usr
+}
+
+check() {
+  cd ${srcdir}/binutils-build
+
+  # do not abort on errors - manually check log files
+  make -k -j1 check || true
 }
 
 package() {
-  cd ${srcdir}/build
+  cd ${srcdir}/binutils-build
   make prefix=${pkgdir}/usr tooldir=${pkgdir}/usr install
-  install -m644 ${srcdir}/include/libiberty.h ${pkgdir}/usr/include
+  
+  # Add some useful headers
+  install -m644 ${srcdir}/binutils/include/libiberty.h ${pkgdir}/usr/include
+  install -m644 ${srcdir}/binutils/include/demangle.h ${pkgdir}/usr/include
 
   # Rebuild libiberty.a with -fPIC
   make -C libiberty clean
@@ -60,9 +66,10 @@ package() {
   make CFLAGS="$CFLAGS -fPIC -fvisibility=hidden" -C bfd
   install -m644 bfd/libbfd.a ${pkgdir}/usr/lib
 
+  # Remove Windows/Novell specific man pages
   rm -f ${pkgdir}/usr/share/man/man1/{dlltool,nlmconv,windres,windmc}*
 
-  # Remove these symlinks, with binutils prereleases they are not ABI stable.
+  # Remove these symlinks, they are not ABI stable.
   # Programs should compile static to the .a file.
   rm -f ${pkgdir}/usr/lib/lib{bfd,opcodes}.so
   echo "INPUT ( /usr/lib/libbfd.a -liberty -lz )" >${pkgdir}/usr/lib/libbfd.so
